server:
  port: 8083

spring:
  application:
    name: keycloak-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: ${KEYCLOAK_SECRET:test}
    user:
      clientId: spring-security
    realm: test-realm
    serverUrl: http://localhost:9090

  kafka:
    topics:
      passenger:
        name: passenger-topic
        partitions: 1
        replicas: 1
      driver:
        name: driver-topic
        partitions: 1
        replicas: 1

    producer:
      bootstrap-servers: localhost:9092

