spring:
  application:
    name: price-service

  datasource:
    url: ${DATASOURCE_URL:test}
    username: ${DATASOURCE_USERNAME:test}
    password: ${DATASOURCE_PASSWORD:test}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.cache.hibernate.cache.use_second_level_cache: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

