server:
  port: 8087

spring:
  application:
    name: price-service

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.cache.hibernate.cache.use_second_level_cache: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  endpoint:
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  config: classpath:logback-spring.xml

