server:
  port: 8084

spring:
  application:
    name: rides-service

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/ride_db}
    username: ${DATASOURCE_USERNAME:vitya}
    password: ${DATASOURCE_PASSWORD:22817}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092

app:
  kafka:
    consumer:
      topic: available-drivers-topic
      group-id: rides-group
    driver-status-producer:
      topic: driver-status-topic
      group-id: rides-group
    driver-notifications-producer:
      topic: driver-notifications-topic

  feign-clients:
    driver-service:
      url: driver-service
    passenger-service:
      url: passenger-service
    rating-service:
      url: rating-service
    payment-service:
      url: payment-service
    price-service:
      url: price-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/