server:
  port: 8085

spring:
  application:
    name: rating-service

  datasource:
    url: ${DATASOURCE_URL:test}
    username: ${DATASOURCE_USERNAME:test}
    password: ${DATASOURCE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
