server:
  port: 8086

spring:
  application:
    name: promocode-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/promocode_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

