server:
  port: 8086

spring:
  application:
    name: promocode-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/promocode_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  endpoint:
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  config: classpath:logback-spring.xml
