services:

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/