services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: vitya
      POSTGRES_PASSWORD: 22817
    networks:
      - keycloak_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACK CHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
      KC_DB_USERNAME: vitya
      KC_DB_PASSWORD: 22817
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network
    command: [ "start", "--import-realm" ]
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/

volumes:
  postgres_data:
    driver: local

networks:
  keycloak_network:
    driver: bridge