server:
  port: 8081

spring:
  application:
    name: driver-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/driver_db}
    username: ${DATASOURCE_USERNAME:vitya}
    password: ${DATASOURCE_PASSWORD:22817}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true


  kafka:
      bootstrap-servers: localhost:29092

app:
  kafka:
    consumer:
      topic: driver-topic
      group-id: driver-group
      type-mappings: "by.modsen.authservice.dto.NewUserDto:by.modsen.driverservice.kafka.NewUserDto"
    consumer-2:
      topic: requested-rides-topic
      group-id: driver-group
    producer:
      topic: available-drivers-topic
    driver-status-consumer:
      topic: driver-status-topic
      group-id: driver-group
    rating-producer:
      topic: driver-rating-topic

  feign-clients:
    rating-service:
      url: rating-service
    payment-service:
      url: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  endpoint:
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  config: classpath:logback-spring.xml
