global:
  scrape_interval: 5s  # Как часто запрашивать метрики

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.17.0.1:8080',
                   '172.17.0.1:8081',
                   '172.17.0.1:8083',
                   '172.17.0.1:8084',
                   '172.17.0.1:8085',
                   '172.17.0.1:8086',
                   '172.17.0.1:8087',
                   '172.17.0.1:8088']
