### TODO: Тут тоже возня с портами
### TODO: docker.host.internal:8080 работает только windows & macos
### TODO: для Linux надо указывать IP своей машины: 172.17.0.1:8080

global:
  scrape_interval: 5s  # Как часто запрашивать метрики

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']

