server:
  port: 8080

spring:
  application:
    name: passenger-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/passenger_db}
    username: ${DATASOURCE_USERNAME:vitya}
    password: ${DATASOURCE_PASSWORD:22817}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  kafka:
    consumer:
      topic: passenger-topic
      group-id: passenger-group
      bootstrap-servers: localhost:9092
      type-mappings: "by.modsen.keycloakservice.dto.NewUserDto:by.modsen.passengerservice.kafka.NewUserDto"

# Мозолит глаза когда не включена Kafka
logging:
  level:
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients: ERROR
