server:
  port: 8080

spring:
  application:
    name: passenger-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/passenger_db}
    username: ${DATASOURCE_USERNAME:vitya}
    password: ${DATASOURCE_PASSWORD:22817}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092


app:
  kafka:
    consumer:
      topic: passenger-topic
      group-id: passenger-group
      type-mappings: "by.modsen.authservice.dto.NewUserDto:by.modsen.passengerservice.kafka.NewUserDto"

  feign-clients:
    rating-service:
      url: rating-service
    payment-service:
      url: payment-service


## Мозолит глаза когда не включена Kafka
#logging:
#  level:
#    org.apache.kafka.clients.NetworkClient: ERROR
#    org.apache.kafka.clients: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

